import type { Metadata } from "next";
import { GeistSans, GeistMono } from "geist/font"; 
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import { CartProvider } from "./components/cartContext/CartContext";
import HomePage from "./components/HomePage";
import { ToastContainer } from "react-toastify";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${GeistSans.variable} ${GeistMono.variable}`}>
      <body className="antialiased">
        <CartProvider>
          <div className="mx-auto p-4 sm:max-w-xl md:max-w-2xl lg:max-w-3xl xl:max-w-6xl">
            <Navbar />
            <HomePage />
            {children} 
            <Footer />
          </div>
        </CartProvider>
        <ToastContainer position="bottom-right" />
      </body>
    </html>
  );
}
